services:
  - type: web
    name: gymothy-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_DB
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: gymothy-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://gymothy-backend.onrender.com/auth/google/callback
      - key: FRONTEND_URL
        value: https://gymothy.onrender.com

databases:
  - name: gymothy-db
    databaseName: gymothy
    user: gymothy
    plan: free 