services:
  - type: web
    name: gymothy-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: USE_DB
        value: true
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false 